package com.baobaotao.domain;
// Generated 2016-12-19 13:45:05 by Hibernate Tools 5.2.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * TmsSOrder generated by hbm2java
 */
public class TmsSOrder implements java.io.Serializable {

	private Integer id;
	private String orderId;
	private String tmsOrderCode;
	private String mallOrderCode;
	private String orderType;
	private Byte orderStatus;
	private Date orderTime;
	private Date oldArrivalStartTime;
	private Date oldArrivalEndTime;
	private Date estimateArrivalEndTime;
	private Date estimateArrivalStartTime;
	private Float orderAmount;
	private Float bagWeight;
	private String customerId;
	private String customerName;
	private String receiverName;
	private String province;
	private String city;
	private String district;
	private String customerAddress;
	private String customerMobile;
	private Date createDate;
	private Date updataDate;
	private BigDecimal longitude;
	private BigDecimal latitude;
	private String remark;
	private String bak1;
	private String bak2;
	private String bak3;
	private String bak4;
	private String bak5;
	private String bak6;

	public TmsSOrder() {
	}

	public TmsSOrder(Date orderTime, Date oldArrivalStartTime, Date oldArrivalEndTime, Date estimateArrivalEndTime,
			Date estimateArrivalStartTime, Date createDate, Date updataDate) {
		this.orderTime = orderTime;
		this.oldArrivalStartTime = oldArrivalStartTime;
		this.oldArrivalEndTime = oldArrivalEndTime;
		this.estimateArrivalEndTime = estimateArrivalEndTime;
		this.estimateArrivalStartTime = estimateArrivalStartTime;
		this.createDate = createDate;
		this.updataDate = updataDate;
	}

	public TmsSOrder(String orderId, String tmsOrderCode, String mallOrderCode, String orderType, Byte orderStatus,
			Date orderTime, Date oldArrivalStartTime, Date oldArrivalEndTime, Date estimateArrivalEndTime,
			Date estimateArrivalStartTime, Float orderAmount, Float bagWeight, String customerId, String customerName,
			String receiverName, String province, String city, String district, String customerAddress,
			String customerMobile, Date createDate, Date updataDate, BigDecimal longitude, BigDecimal latitude,
			String remark, String bak1, String bak2, String bak3, String bak4, String bak5, String bak6) {
		this.orderId = orderId;
		this.tmsOrderCode = tmsOrderCode;
		this.mallOrderCode = mallOrderCode;
		this.orderType = orderType;
		this.orderStatus = orderStatus;
		this.orderTime = orderTime;
		this.oldArrivalStartTime = oldArrivalStartTime;
		this.oldArrivalEndTime = oldArrivalEndTime;
		this.estimateArrivalEndTime = estimateArrivalEndTime;
		this.estimateArrivalStartTime = estimateArrivalStartTime;
		this.orderAmount = orderAmount;
		this.bagWeight = bagWeight;
		this.customerId = customerId;
		this.customerName = customerName;
		this.receiverName = receiverName;
		this.province = province;
		this.city = city;
		this.district = district;
		this.customerAddress = customerAddress;
		this.customerMobile = customerMobile;
		this.createDate = createDate;
		this.updataDate = updataDate;
		this.longitude = longitude;
		this.latitude = latitude;
		this.remark = remark;
		this.bak1 = bak1;
		this.bak2 = bak2;
		this.bak3 = bak3;
		this.bak4 = bak4;
		this.bak5 = bak5;
		this.bak6 = bak6;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getOrderId() {
		return this.orderId;
	}

	public void setOrderId(String orderId) {
		this.orderId = orderId;
	}

	public String getTmsOrderCode() {
		return this.tmsOrderCode;
	}

	public void setTmsOrderCode(String tmsOrderCode) {
		this.tmsOrderCode = tmsOrderCode;
	}

	public String getMallOrderCode() {
		return this.mallOrderCode;
	}

	public void setMallOrderCode(String mallOrderCode) {
		this.mallOrderCode = mallOrderCode;
	}

	public String getOrderType() {
		return this.orderType;
	}

	public void setOrderType(String orderType) {
		this.orderType = orderType;
	}

	public Byte getOrderStatus() {
		return this.orderStatus;
	}

	public void setOrderStatus(Byte orderStatus) {
		this.orderStatus = orderStatus;
	}

	public Date getOrderTime() {
		return this.orderTime;
	}

	public void setOrderTime(Date orderTime) {
		this.orderTime = orderTime;
	}

	public Date getOldArrivalStartTime() {
		return this.oldArrivalStartTime;
	}

	public void setOldArrivalStartTime(Date oldArrivalStartTime) {
		this.oldArrivalStartTime = oldArrivalStartTime;
	}

	public Date getOldArrivalEndTime() {
		return this.oldArrivalEndTime;
	}

	public void setOldArrivalEndTime(Date oldArrivalEndTime) {
		this.oldArrivalEndTime = oldArrivalEndTime;
	}

	public Date getEstimateArrivalEndTime() {
		return this.estimateArrivalEndTime;
	}

	public void setEstimateArrivalEndTime(Date estimateArrivalEndTime) {
		this.estimateArrivalEndTime = estimateArrivalEndTime;
	}

	public Date getEstimateArrivalStartTime() {
		return this.estimateArrivalStartTime;
	}

	public void setEstimateArrivalStartTime(Date estimateArrivalStartTime) {
		this.estimateArrivalStartTime = estimateArrivalStartTime;
	}

	public Float getOrderAmount() {
		return this.orderAmount;
	}

	public void setOrderAmount(Float orderAmount) {
		this.orderAmount = orderAmount;
	}

	public Float getBagWeight() {
		return this.bagWeight;
	}

	public void setBagWeight(Float bagWeight) {
		this.bagWeight = bagWeight;
	}

	public String getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(String customerId) {
		this.customerId = customerId;
	}

	public String getCustomerName() {
		return this.customerName;
	}

	public void setCustomerName(String customerName) {
		this.customerName = customerName;
	}

	public String getReceiverName() {
		return this.receiverName;
	}

	public void setReceiverName(String receiverName) {
		this.receiverName = receiverName;
	}

	public String getProvince() {
		return this.province;
	}

	public void setProvince(String province) {
		this.province = province;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getDistrict() {
		return this.district;
	}

	public void setDistrict(String district) {
		this.district = district;
	}

	public String getCustomerAddress() {
		return this.customerAddress;
	}

	public void setCustomerAddress(String customerAddress) {
		this.customerAddress = customerAddress;
	}

	public String getCustomerMobile() {
		return this.customerMobile;
	}

	public void setCustomerMobile(String customerMobile) {
		this.customerMobile = customerMobile;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public Date getUpdataDate() {
		return this.updataDate;
	}

	public void setUpdataDate(Date updataDate) {
		this.updataDate = updataDate;
	}

	public BigDecimal getLongitude() {
		return this.longitude;
	}

	public void setLongitude(BigDecimal longitude) {
		this.longitude = longitude;
	}

	public BigDecimal getLatitude() {
		return this.latitude;
	}

	public void setLatitude(BigDecimal latitude) {
		this.latitude = latitude;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public String getBak1() {
		return this.bak1;
	}

	public void setBak1(String bak1) {
		this.bak1 = bak1;
	}

	public String getBak2() {
		return this.bak2;
	}

	public void setBak2(String bak2) {
		this.bak2 = bak2;
	}

	public String getBak3() {
		return this.bak3;
	}

	public void setBak3(String bak3) {
		this.bak3 = bak3;
	}

	public String getBak4() {
		return this.bak4;
	}

	public void setBak4(String bak4) {
		this.bak4 = bak4;
	}

	public String getBak5() {
		return this.bak5;
	}

	public void setBak5(String bak5) {
		this.bak5 = bak5;
	}

	public String getBak6() {
		return this.bak6;
	}

	public void setBak6(String bak6) {
		this.bak6 = bak6;
	}

}
